version: '3.8'

services:
  db:
    image: postgres:14
    container_name: user_service_db
    environment:
      POSTGRES_DB: user_service_db   # Название базы данных
      POSTGRES_USER: user           # Имя пользователя
      POSTGRES_PASSWORD: password   # Пароль
    ports:
      - "5432:5432"                 # Пробрасываем порт PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data   # Сохраняем данные базы данных
    networks:
      - user_service_network
    restart: always

networks:
  user_service_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
