version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    restart: on-failure
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - task_manager_network

  kafka:
    image: bitnami/kafka:latest
    restart: on-failure
    ports:
      - "9092:9092"  # EXTERNAL listener
      - "29092:29092"  # INTERNAL listener (для связи между контейнерами)
    environment:
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092,INTERNAL://kafka:29092
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper
    networks:
      - task_manager_network

  db:
    image: postgres:14
    container_name: user_service_db
    environment:
      POSTGRES_DB: user_service_db   # Название базы данных
      POSTGRES_USER: user           # Имя пользователя
      POSTGRES_PASSWORD: password   # Пароль
    ports:
      - "5432:5432"                 # Пробрасываем порт PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data   # Сохраняем данные базы данных
    networks:
      - task_manager_network
    restart: always

networks:
  task_manager_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
